tmp_dir = "tmp"

[build]
cmd = "sqlc generate && go build -o ./tmp/main ./cmd/web"
bin = "tmp/main"
include_ext = ["go", "sql"]
exclude_dir = [
    "tmp",
    "testdata",
    "vendor",
    "web",
    "internal/storage/postgres/sqlc",
    "internal/storage/postgres/schema",
    "internal/storage/postgres/migrations"
]
exclude_regex = ["_test.go"]

[log]
time = true