// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Movie struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Director    sql.NullString `json:"director"`
	ReleaseYear sql.NullInt32  `json:"release_year"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
