// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_review.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addReview = `-- name: AddReview :one
INSERT INTO reviews (user_id, movie_id, comment, created_at)
VALUES ($1, $2, $3, $4)
RETURNING user_id, movie_id, comment, created_at
`

type AddReviewParams struct {
	UserID    int64     `json:"user_id"`
	MovieID   int64     `json:"movie_id"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
}

// noinspection SqlResolve
func (q *Queries) AddReview(ctx context.Context, arg AddReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, addReview,
		arg.UserID,
		arg.MovieID,
		arg.Comment,
		arg.CreatedAt,
	)
	var i Review
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :one
DELETE FROM reviews
WHERE user_id = $1 AND movie_id = $2
RETURNING user_id, movie_id, comment, created_at
`

type DeleteReviewParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

// noinspection SqlResolve
func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, deleteReview, arg.UserID, arg.MovieID)
	var i Review
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT user_id, movie_id, comment, created_at
FROM reviews
WHERE user_id = $1 AND movie_id = $2
`

type GetReviewParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

// noinspection SqlResolve
func (q *Queries) GetReview(ctx context.Context, arg GetReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReview, arg.UserID, arg.MovieID)
	var i Review
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listMovieReviews = `-- name: ListMovieReviews :many
SELECT rev.user_id, rev.movie_id, rev.comment, rev.created_at
FROM movies AS mov
LEFT JOIN reviews AS rev
ON (rev.movie_id = mov.id)
WHERE mov.id = $1
LIMIT $2
OFFSET $3
`

type ListMovieReviewsParams struct {
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMovieReviewsRow struct {
	UserID    sql.NullInt64  `json:"user_id"`
	MovieID   sql.NullInt64  `json:"movie_id"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

// noinspection SqlResolve
func (q *Queries) ListMovieReviews(ctx context.Context, arg ListMovieReviewsParams) ([]ListMovieReviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMovieReviews, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovieReviewsRow
	for rows.Next() {
		var i ListMovieReviewsRow
		if err := rows.Scan(
			&i.UserID,
			&i.MovieID,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserReviews = `-- name: ListUserReviews :many
SELECT rev.user_id, rev.movie_id, rev.comment, rev.created_at
FROM users AS usr
LEFT JOIN reviews AS rev
ON (rev.user_id = usr.id)
WHERE usr.id = $1
LIMIT $2
OFFSET $3
`

type ListUserReviewsParams struct {
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUserReviewsRow struct {
	UserID    sql.NullInt64  `json:"user_id"`
	MovieID   sql.NullInt64  `json:"movie_id"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

// noinspection SqlResolve
func (q *Queries) ListUserReviews(ctx context.Context, arg ListUserReviewsParams) ([]ListUserReviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserReviews, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserReviewsRow
	for rows.Next() {
		var i ListUserReviewsRow
		if err := rows.Scan(
			&i.UserID,
			&i.MovieID,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET comment = $3
WHERE user_id = $1 AND movie_id = $2
RETURNING user_id, movie_id, comment, created_at
`

type UpdateReviewParams struct {
	UserID  int64  `json:"user_id"`
	MovieID int64  `json:"movie_id"`
	Comment string `json:"comment"`
}

// noinspection SqlResolve
func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, updateReview, arg.UserID, arg.MovieID, arg.Comment)
	var i Review
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}
