// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_movie.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addMovie = `-- name: AddMovie :one
INSERT INTO movies (title, synopsis, released_at, duration_minutes, poster_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, synopsis, released_at, poster_url, duration_minutes
`

type AddMovieParams struct {
	Title           string         `json:"title"`
	Synopsis        string         `json:"synopsis"`
	ReleasedAt      time.Time      `json:"released_at"`
	DurationMinutes int32          `json:"duration_minutes"`
	PosterUrl       sql.NullString `json:"poster_url"`
}

func (q *Queries) AddMovie(ctx context.Context, arg AddMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, addMovie,
		arg.Title,
		arg.Synopsis,
		arg.ReleasedAt,
		arg.DurationMinutes,
		arg.PosterUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Synopsis,
		&i.ReleasedAt,
		&i.PosterUrl,
		&i.DurationMinutes,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :one
DELETE FROM movies
WHERE id = $1
RETURNING id, title, synopsis, released_at, poster_url, duration_minutes
`

func (q *Queries) DeleteMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRowContext(ctx, deleteMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Synopsis,
		&i.ReleasedAt,
		&i.PosterUrl,
		&i.DurationMinutes,
	)
	return i, err
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, synopsis, released_at, poster_url, duration_minutes
FROM movies
WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Synopsis,
		&i.ReleasedAt,
		&i.PosterUrl,
		&i.DurationMinutes,
	)
	return i, err
}

const listCelebrityMovies = `-- name: ListCelebrityMovies :many
SELECT mov.id, mov.title, mov.synopsis, mov.released_at, mov.poster_url, mov.duration_minutes
FROM roles AS rol
JOIN movies AS mov
ON (mov.id = rol.movie_id)
WHERE rol.celebrity_id = $1
ORDER BY mov.released_at DESC
LIMIT $2
OFFSET $3
`

type ListCelebrityMoviesParams struct {
	CelebrityID int64 `json:"celebrity_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListCelebrityMovies(ctx context.Context, arg ListCelebrityMoviesParams) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listCelebrityMovies, arg.CelebrityID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Synopsis,
			&i.ReleasedAt,
			&i.PosterUrl,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenreMovies = `-- name: ListGenreMovies :many
SELECT mov.id, mov.title, mov.synopsis, mov.released_at, mov.poster_url, mov.duration_minutes
FROM genres AS gen
LEFT JOIN categories AS cat
ON (cat.genre_id = gen.id)
LEFT JOIN movies AS mov
ON (cat.movie_id = mov.id)
WHERE gen.id = $1
LIMIT $2
OFFSET $3
`

type ListGenreMoviesParams struct {
	ID     int32 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListGenreMoviesRow struct {
	ID              sql.NullInt64  `json:"id"`
	Title           sql.NullString `json:"title"`
	Synopsis        sql.NullString `json:"synopsis"`
	ReleasedAt      sql.NullTime   `json:"released_at"`
	PosterUrl       sql.NullString `json:"poster_url"`
	DurationMinutes sql.NullInt32  `json:"duration_minutes"`
}

func (q *Queries) ListGenreMovies(ctx context.Context, arg ListGenreMoviesParams) ([]ListGenreMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGenreMovies, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenreMoviesRow
	for rows.Next() {
		var i ListGenreMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Synopsis,
			&i.ReleasedAt,
			&i.PosterUrl,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, synopsis, released_at, poster_url, duration_minutes
FROM movies
ORDER BY released_at DESC
LIMIT $1
OFFSET $2
`

type ListMoviesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMovies(ctx context.Context, arg ListMoviesParams) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listMovies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Synopsis,
			&i.ReleasedAt,
			&i.PosterUrl,
			&i.DurationMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET title = $2,
    synopsis = $3,
    released_at = $4,
    duration_minutes = $5,
    poster_url = $6
WHERE id = $1
RETURNING id, title, synopsis, released_at, poster_url, duration_minutes
`

type UpdateMovieParams struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Synopsis        string         `json:"synopsis"`
	ReleasedAt      time.Time      `json:"released_at"`
	DurationMinutes int32          `json:"duration_minutes"`
	PosterUrl       sql.NullString `json:"poster_url"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Synopsis,
		arg.ReleasedAt,
		arg.DurationMinutes,
		arg.PosterUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Synopsis,
		&i.ReleasedAt,
		&i.PosterUrl,
		&i.DurationMinutes,
	)
	return i, err
}
