// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_rating.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addRating = `-- name: AddRating :one
INSERT INTO ratings (user_id, movie_id, rating)
VALUES ($1, $2, $3)
RETURNING user_id, movie_id, rating, created_at
`

type AddRatingParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
	Rating  int32 `json:"rating"`
}

// noinspection SqlResolve
func (q *Queries) AddRating(ctx context.Context, arg AddRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, addRating, arg.UserID, arg.MovieID, arg.Rating)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRating = `-- name: DeleteRating :one
DELETE FROM ratings
WHERE user_id = $1 AND movie_id = $2
RETURNING user_id, movie_id, rating, created_at
`

type DeleteRatingParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

// noinspection SqlResolve
func (q *Queries) DeleteRating(ctx context.Context, arg DeleteRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, deleteRating, arg.UserID, arg.MovieID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const getRating = `-- name: GetRating :one
SELECT user_id, movie_id, rating, created_at
FROM ratings
WHERE user_id = $1 AND movie_id = $2
`

type GetRatingParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

// noinspection SqlResolve
func (q *Queries) GetRating(ctx context.Context, arg GetRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, getRating, arg.UserID, arg.MovieID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const listMovieRatings = `-- name: ListMovieRatings :many
SELECT rat.user_id, rat.movie_id, rat.rating, rat.created_at
FROM movies AS mov
LEFT JOIN ratings AS rat
ON (rat.movie_id = mov.id)
WHERE mov.id = $1
ORDER BY rat.rating DESC
LIMIT $2
OFFSET $3
`

type ListMovieRatingsParams struct {
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMovieRatingsRow struct {
	UserID    sql.NullInt64 `json:"user_id"`
	MovieID   sql.NullInt64 `json:"movie_id"`
	Rating    sql.NullInt32 `json:"rating"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

// noinspection SqlResolve
func (q *Queries) ListMovieRatings(ctx context.Context, arg ListMovieRatingsParams) ([]ListMovieRatingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMovieRatings, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovieRatingsRow
	for rows.Next() {
		var i ListMovieRatingsRow
		if err := rows.Scan(
			&i.UserID,
			&i.MovieID,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRatings = `-- name: ListUserRatings :many
SELECT rat.user_id, rat.movie_id, rat.rating, rat.created_at
FROM users AS usr
LEFT JOIN ratings AS rat
ON (rat.user_id = usr.id)
WHERE usr.id = $1
ORDER BY rat.created_at DESC
LIMIT $2
OFFSET $3
`

type ListUserRatingsParams struct {
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUserRatingsRow struct {
	UserID    sql.NullInt64 `json:"user_id"`
	MovieID   sql.NullInt64 `json:"movie_id"`
	Rating    sql.NullInt32 `json:"rating"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

// noinspection SqlResolve
func (q *Queries) ListUserRatings(ctx context.Context, arg ListUserRatingsParams) ([]ListUserRatingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRatings, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRatingsRow
	for rows.Next() {
		var i ListUserRatingsRow
		if err := rows.Scan(
			&i.UserID,
			&i.MovieID,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRating = `-- name: UpdateRating :one
UPDATE ratings
SET rating = $3
WHERE user_id = $1 AND movie_id = $2
RETURNING user_id, movie_id, rating, created_at
`

type UpdateRatingParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
	Rating  int32 `json:"rating"`
}

// noinspection SqlResolve
func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, updateRating, arg.UserID, arg.MovieID, arg.Rating)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}
