// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_rating.sql

package sqlc

import (
	"context"
)

const addRating = `-- name: AddRating :one
INSERT INTO ratings (user_id, movie_id, rating)
VALUES ($1, $2, $3)
RETURNING user_id, movie_id, rating, created_at
`

type AddRatingParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
	Rating  int32 `json:"rating"`
}

func (q *Queries) AddRating(ctx context.Context, arg AddRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, addRating, arg.UserID, arg.MovieID, arg.Rating)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRating = `-- name: DeleteRating :exec
DELETE FROM ratings
WHERE user_id = $1 AND movie_id = $2
`

type DeleteRatingParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) DeleteRating(ctx context.Context, arg DeleteRatingParams) error {
	_, err := q.db.ExecContext(ctx, deleteRating, arg.UserID, arg.MovieID)
	return err
}

const getRating = `-- name: GetRating :one
SELECT user_id, movie_id, rating, created_at
FROM ratings
WHERE user_id = $1 AND movie_id = $2
`

type GetRatingParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) GetRating(ctx context.Context, arg GetRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, getRating, arg.UserID, arg.MovieID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const listMovieRatings = `-- name: ListMovieRatings :many
SELECT rat.user_id, rat.movie_id, rat.rating, rat.created_at
FROM ratings AS rat
JOIN users AS usr
ON (usr.id = rat.user_id)
WHERE rat.movie_id = $1
ORDER BY rat.rating DESC
LIMIT $2
OFFSET $3
`

type ListMovieRatingsParams struct {
	MovieID int64 `json:"movie_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListMovieRatings(ctx context.Context, arg ListMovieRatingsParams) ([]Rating, error) {
	rows, err := q.db.QueryContext(ctx, listMovieRatings, arg.MovieID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.UserID,
			&i.MovieID,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRatings = `-- name: ListUserRatings :many
SELECT rat.user_id, rat.movie_id, rat.rating, rat.created_at
FROM ratings AS rat
JOIN movies AS mov
ON (mov.id = rat.movie_id)
WHERE rat.user_id = $1
ORDER BY rat.created_at DESC
LIMIT $2
OFFSET $3
`

type ListUserRatingsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUserRatings(ctx context.Context, arg ListUserRatingsParams) ([]Rating, error) {
	rows, err := q.db.QueryContext(ctx, listUserRatings, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.UserID,
			&i.MovieID,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRating = `-- name: UpdateRating :one
UPDATE ratings
SET rating = $3
WHERE user_id = $1 AND movie_id = $2
RETURNING user_id, movie_id, rating, created_at
`

type UpdateRatingParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
	Rating  int32 `json:"rating"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, updateRating, arg.UserID, arg.MovieID, arg.Rating)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}
