// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_role.sql

package sqlc

import (
	"context"
)

const addRole = `-- name: AddRole :one
INSERT INTO roles (movie_id, celebrity_id, role)
VALUES ($1, $2, $3)
RETURNING celebrity_id, movie_id, role
`

type AddRoleParams struct {
	MovieID     int64  `json:"movie_id"`
	CelebrityID int64  `json:"celebrity_id"`
	Role        string `json:"role"`
}

func (q *Queries) AddRole(ctx context.Context, arg AddRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, addRole, arg.MovieID, arg.CelebrityID, arg.Role)
	var i Role
	err := row.Scan(&i.CelebrityID, &i.MovieID, &i.Role)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE movie_id = $1 AND celebrity_id = $2
`

type DeleteRoleParams struct {
	MovieID     int64 `json:"movie_id"`
	CelebrityID int64 `json:"celebrity_id"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRole, arg.MovieID, arg.CelebrityID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT celebrity_id, movie_id, role
FROM roles
WHERE movie_id = $1 AND celebrity_id = $2
`

type GetRoleParams struct {
	MovieID     int64 `json:"movie_id"`
	CelebrityID int64 `json:"celebrity_id"`
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, arg.MovieID, arg.CelebrityID)
	var i Role
	err := row.Scan(&i.CelebrityID, &i.MovieID, &i.Role)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET role = $3
WHERE movie_id = $1 AND celebrity_id = $2
RETURNING celebrity_id, movie_id, role
`

type UpdateRoleParams struct {
	MovieID     int64  `json:"movie_id"`
	CelebrityID int64  `json:"celebrity_id"`
	Role        string `json:"role"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole, arg.MovieID, arg.CelebrityID, arg.Role)
	var i Role
	err := row.Scan(&i.CelebrityID, &i.MovieID, &i.Role)
	return i, err
}
