// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_genre.sql

package sqlc

import (
	"context"
)

const addGenre = `-- name: AddGenre :one
INSERT INTO genres (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) AddGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRowContext(ctx, addGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteGenre = `-- name: DeleteGenre :exec
DELETE FROM genres
WHERE id = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteGenre, id)
	return err
}

const getGenre = `-- name: GetGenre :one
SELECT id, name
FROM genres
WHERE id = $1
`

func (q *Queries) GetGenre(ctx context.Context, id int32) (Genre, error) {
	row := q.db.QueryRowContext(ctx, getGenre, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listGenres = `-- name: ListGenres :many
SELECT id, name
FROM genres
LIMIT $1
OFFSET $2
`

type ListGenresParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGenres(ctx context.Context, arg ListGenresParams) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, listGenres, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovieGenres = `-- name: ListMovieGenres :many
SELECT gen.id, gen.name
FROM categories AS cat
JOIN genres AS gen
ON (cat.genre_id = gen.id)
WHERE cat.movie_id = $1
LIMIT $2
OFFSET $3
`

type ListMovieGenresParams struct {
	MovieID int64 `json:"movie_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListMovieGenres(ctx context.Context, arg ListMovieGenresParams) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, listMovieGenres, arg.MovieID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenre = `-- name: UpdateGenre :one
UPDATE genres
SET name = $2
WHERE id = $1
RETURNING id, name
`

type UpdateGenreParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateGenre(ctx context.Context, arg UpdateGenreParams) (Genre, error) {
	row := q.db.QueryRowContext(ctx, updateGenre, arg.ID, arg.Name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
