// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_category.sql

package sqlc

import (
	"context"
)

const addCategory = `-- name: AddCategory :exec
INSERT INTO categories (genre_id, movie_id)
VALUES ($1, $2)
`

type AddCategoryParams struct {
	GenreID int32 `json:"genre_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) AddCategory(ctx context.Context, arg AddCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addCategory, arg.GenreID, arg.MovieID)
	return err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM categories
WHERE genre_id = $1 AND movie_id = $2
RETURNING genre_id, movie_id
`

type DeleteCategoryParams struct {
	GenreID int32 `json:"genre_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, deleteCategory, arg.GenreID, arg.MovieID)
	var i Category
	err := row.Scan(&i.GenreID, &i.MovieID)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT genre_id, movie_id
FROM categories
WHERE genre_id = $1 AND movie_id = $2
`

type GetCategoryParams struct {
	GenreID int32 `json:"genre_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, arg.GenreID, arg.MovieID)
	var i Category
	err := row.Scan(&i.GenreID, &i.MovieID)
	return i, err
}
