// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/movies": {
            "get": {
                "description": "Obtiene una lista de películas, ordenada por fecha de estreno descendente, con paginación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Lista películas paginadas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de página",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Cantidad de filas por página",
                        "name": "rows",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de películas exitosa",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.Movie"
                            }
                        }
                    },
                    "400": {
                        "description": "Error de validación en parámetros",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    }
                }
            },
            "post": {
                "description": "Agrega una nueva película al catálogo usando el formato JSON. La URL del póster puede omitirse.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Agrega una película",
                "parameters": [
                    {
                        "description": "Número de página",
                        "name": "movie",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.AddMovieInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de películas exitosa",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.Movie"
                            }
                        }
                    },
                    "400": {
                        "description": "Error de validación en parámetros",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    }
                }
            }
        },
        "/movies/{id1}/genres": {
            "get": {
                "description": "Obtiene la lista de géneros asociados a una película específica.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies",
                    "Genres"
                ],
                "summary": "Lista todos los géneros de una película",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la película",
                        "name": "id1",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de géneros exitosa",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.Genre"
                            }
                        }
                    },
                    "400": {
                        "description": "Error de validación en el ID de la película",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    }
                }
            }
        },
        "/movies/{id1}/genres/{id2}": {
            "get": {
                "description": "Obtiene la información de un género específico asociado a una película, dado su ID de género.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies",
                    "Genres"
                ],
                "summary": "Obtiene un género asociado a una película (Por su ID de género)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la película",
                        "name": "id1",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID del género",
                        "name": "id2",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Género encontrado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/service.Genre"
                        }
                    },
                    "400": {
                        "description": "Error de validación en el ID",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    },
                    "404": {
                        "description": "Género no encontrado para esa película",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    }
                }
            }
        },
        "/movies/{id}": {
            "get": {
                "description": "Obtiene toda la información asociada a una película dado su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Obtener una película",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la película a obtener",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Película obtenida exitosamente"
                    },
                    "404": {
                        "description": "Película no encontrada",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza toda la información de una película. Todos los campos son requeridos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Actualiza los datos de una película",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la película a actualizar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Número de página",
                        "name": "movie",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateMovieInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Actualización de película exitosa",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.Movie"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros inválidos",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    },
                    "404": {
                        "description": "Película no encontrada",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Borra una película del catálogo permanentemente con su ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Borra una película",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la película a eliminar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Película eliminada exitosamente"
                    },
                    "400": {
                        "description": "Película no eliminable",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    },
                    "404": {
                        "description": "Película no encontrada",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/api.JsonError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.JsonError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "service.AddMovieInput": {
            "type": "object",
            "required": [
                "duration_minutes",
                "released_at",
                "synopsis",
                "title"
            ],
            "properties": {
                "duration_minutes": {
                    "type": "integer",
                    "minimum": 1
                },
                "poster_url": {
                    "type": "string"
                },
                "released_at": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string",
                    "maxLength": 5000
                },
                "title": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "service.Genre": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.Movie": {
            "type": "object",
            "properties": {
                "duration_minutes": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "poster_url": {
                    "type": "string"
                },
                "released_at": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "service.UpdateMovieInput": {
            "type": "object",
            "properties": {
                "duration_minutes": {
                    "type": "integer"
                },
                "poster_url": {
                    "type": "string"
                },
                "released_at": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API de Películas UNICEN",
	Description:      "Esta es la API REST para la aplicación de gestión de películas.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
