basePath: /api
definitions:
  api.JsonError:
    properties:
      message:
        type: string
    type: object
  service.AddMovieInput:
    properties:
      duration_minutes:
        minimum: 1
        type: integer
      poster_url:
        type: string
      released_at:
        type: string
      synopsis:
        maxLength: 5000
        type: string
      title:
        maxLength: 255
        type: string
    required:
    - duration_minutes
    - released_at
    - synopsis
    - title
    type: object
  service.Genre:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  service.Movie:
    properties:
      duration_minutes:
        example: 255
        type: integer
      id:
        example: 1
        type: integer
      poster_url:
        example: https://imgs.search.brave.com/8beLkj9LsaTyqIIEdbEELICTyQJkSQnTz6UQfl4x5oI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLmVi/YXlpbWcuY29tL2lt/YWdlcy9nL3hwNEFB/ZVN3cGNwb2xKRFQv/cy1sMjI1LmpwZw
        type: string
      released_at:
        example: "2025-10-30T00:00:00Z"
        type: string
      synopsis:
        example: A man that can manipulate every string variable
        type: string
      title:
        example: Lord of the Strings
        type: string
    type: object
  service.UpdateMovieInput:
    properties:
      duration_minutes:
        type: integer
      poster_url:
        type: string
      released_at:
        type: string
      synopsis:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Esta es la API REST para la aplicación de gestión de películas.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API de Películas UNICEN
  version: "1.0"
paths:
  /movies:
    get:
      consumes:
      - application/json
      description: Obtiene una lista de películas, ordenada por fecha de estreno descendente,
        con paginación.
      parameters:
      - description: Número de página
        in: query
        name: page
        required: true
        type: integer
      - description: Cantidad de filas por página
        in: query
        name: rows
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Lista de películas exitosa
          schema:
            items:
              $ref: '#/definitions/service.Movie'
            type: array
        "400":
          description: Error de validación de los parámetros" // {"message":"invalid
            page number"}
          schema:
            $ref: '#/definitions/api.JsonError'
        "500":
          description: "Error interno del servidor\" \t\t\t// {\"message\":\"internal
            server error\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
      summary: Lista películas paginadas
      tags:
      - Movies
    post:
      consumes:
      - application/json
      description: Agrega una nueva película al catálogo. La URL del póster puede
        omitirse.
      parameters:
      - description: Número de página
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/service.AddMovieInput'
      produces:
      - application/json
      responses:
        "201":
          description: Película agregada exitosamente
          schema:
            $ref: '#/definitions/service.Movie'
        "400":
          description: Error de validación de los parámetros" // {"message":"invalid
            page number"}
          schema:
            $ref: '#/definitions/api.JsonError'
        "409":
          description: "Error de duplicacion de recursos\" \t\t// {\"message\":\"the
            given movie already exists\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
        "500":
          description: "Error interno del servidor\"\t\t\t// {\"message\":\"internal
            server error\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
      summary: Agrega una película
      tags:
      - Movies
  /movies/{id}:
    delete:
      consumes:
      - application/json
      description: Borra una película dada por ID permanentemente del catálogo.
      parameters:
      - description: ID de la película a eliminar
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Película eliminada exitosamente
        "400":
          description: Error de validación de los parámetros" // {"message":"invalid
            path identifier"}
          schema:
            $ref: '#/definitions/api.JsonError'
        "404":
          description: "Error por película no encontrada\"\t\t// {\"message\":\"invalid
            movie identifier\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
        "500":
          description: "Error interno del servidor\"\t\t\t// {\"message\":\"internal
            server error\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
      summary: Borra una película
      tags:
      - Movies
    get:
      consumes:
      - application/json
      description: Obtiene toda la información asociada a una película dada por ID.
      parameters:
      - description: ID de la película a obtener
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Película obtenida exitosamente
          schema:
            $ref: '#/definitions/service.Movie'
        "400":
          description: Error de validación de los parámetros" // {"message":"invalid
            path identifier"}
          schema:
            $ref: '#/definitions/api.JsonError'
        "404":
          description: "Error por película no encontrada\" \t\t// {\"message\":\"invalid
            movie identifier\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
        "500":
          description: "Error interno del servidor\"\t\t\t// {\"message\":\"internal
            server error\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
      summary: Obtener una película
      tags:
      - Movies
    put:
      consumes:
      - application/json
      description: Actualiza toda la información de una película dada por ID. Todos
        los campos son requeridos.
      parameters:
      - description: ID de la película a actualizar
        in: path
        name: id
        required: true
        type: integer
      - description: Número de página
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/service.UpdateMovieInput'
      produces:
      - application/json
      responses:
        "200":
          description: Película actualizada exitosamente
          schema:
            $ref: '#/definitions/service.Movie'
        "400":
          description: Error de validación de los parámetros" // {"message":"invalid
            path identifier"}
          schema:
            $ref: '#/definitions/api.JsonError'
        "404":
          description: "Error por película no encontrada\"\t\t// {\"message\":\"invalid
            movie identifier\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
        "409":
          description: "Error de duplicacion de recursos\" \t\t// {\"message\":\"the
            given movie already exists\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
        "500":
          description: "Error interno del servidor\"\t\t\t// {\"message\":\"internal
            server error\"}"
          schema:
            $ref: '#/definitions/api.JsonError'
      summary: Actualiza los datos de una película
      tags:
      - Movies
  /movies/{id1}/genres:
    get:
      consumes:
      - application/json
      description: Obtiene la lista de géneros asociados a una película específica.
      parameters:
      - description: ID de la película
        in: path
        name: id1
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Lista de géneros exitosa
          schema:
            items:
              $ref: '#/definitions/service.Genre'
            type: array
        "400":
          description: Error de validación en el ID de la película
          schema:
            $ref: '#/definitions/api.JsonError'
        "500":
          description: Error interno del servidor
          schema:
            $ref: '#/definitions/api.JsonError'
      summary: Lista todos los géneros de una película
      tags:
      - Movies
      - Genres
  /movies/{id1}/genres/{id2}:
    get:
      consumes:
      - application/json
      description: Obtiene la información de un género específico asociado a una película,
        dado su ID de género.
      parameters:
      - description: ID de la película
        in: path
        name: id1
        required: true
        type: integer
      - description: ID del género
        in: path
        name: id2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Género encontrado exitosamente
          schema:
            $ref: '#/definitions/service.Genre'
        "400":
          description: Error de validación en el ID
          schema:
            $ref: '#/definitions/api.JsonError'
        "404":
          description: Género no encontrado para esa película
          schema:
            $ref: '#/definitions/api.JsonError'
      summary: Obtiene un género asociado a una película (Por su ID de género)
      tags:
      - Movies
      - Genres
swagger: "2.0"
